## NumPy τα απολύτως βασικά

1. Εισαγωγή & seed

In [2]:
import numpy as np

# Αναπαραγωγιμότητα για τυχαίους αριθμούς
np.random.seed(42)

2. Δημιουργία arrays

In [11]:
a = np.array([1, 2, 3])
b = np.arange(0, 10, 2)         # 0,2,4,6,8
c = np.linspace(0, 1, 5)        # 5 τιμές από 0 έως 1
z = np.zeros((2, 3))            # 2x3 μηδενικό
o = np.ones((3, 2))             # 3x2 άσσοι
r = np.random.rand(2, 3)        # ομοιόμορφη [0,1)
ri = np.random.randint(0, 10, size=(2, 3))  # ακέραιοι [0,10)

a, b, c, z, o, r, ri



(array([1, 2, 3]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0.37454012, 0.95071431, 0.73199394],
        [0.59865848, 0.15601864, 0.15599452]]),
 array([[7, 4, 3],
        [7, 7, 2]], dtype=int32))

3. Ιδιότητες array

In [19]:
arr = np.random.rand(3, 4)
print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("ndim:", arr.ndim)
print("size:", arr.size)
print("itemsize:", arr.itemsize, "bytes ανά στοιχείο")



dtype: float64
shape: (3, 4)
ndim: 2
size: 12
itemsize: 8 bytes ανά στοιχείο


4. Indexing & Slicing

In [20]:
x = np.arange(10)
print(x[0], x[-1])         # πρώτο/τελευταίο
print(x[2:7])              # 2..6
print(x[::2])              # step 2

M = np.arange(12).reshape(3, 4)
print("M=\n", M)
print("M[0, 0] =", M[0, 0])
print("M[1, :2] =", M[1, :2])     # γραμμή 1, πρώτες 2 στήλες
print("M[:, -1] =", M[:, -1])     # τελευταία στήλη
print("Block=\n", M[0:2, 1:3])    # 2x2 υποπίνακας


0 9
[2 3 4 5 6]
[0 2 4 6 8]
M=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
M[0, 0] = 0
M[1, :2] = [4 5]
M[:, -1] = [ 3  7 11]
Block=
 [[1 2]
 [5 6]]


5. Boolean masking & filtering

In [21]:
vals = np.random.rand(10)
mask = vals > 0.5
print("vals:", vals)
print("mask:", mask)
filtered = vals[mask]
filtered


vals: [0.29214465 0.36636184 0.45606998 0.78517596 0.19967378 0.51423444
 0.59241457 0.04645041 0.60754485 0.17052412]
mask: [False False False  True False  True  True False  True False]


array([0.78517596, 0.51423444, 0.59241457, 0.60754485])

6. Broadcasting (πρόσθεση vector σε matrix, scaling)

In [22]:
A = np.arange(6).reshape(2, 3)   # shape (2,3)
v = np.array([10, 20, 30])       # shape (3,)
print("A+v=\n", A + v)           # προσθέτει ανά στήλη
print("2*A=\n", 2 * A)           # scaling



A+v=
 [[10 21 32]
 [13 24 35]]
2*A=
 [[ 0  2  4]
 [ 6  8 10]]


7. Συναρτήσεις κατά axis

In [ ]:
B = np.arange(12).reshape(3, 4)
print("sum axis=0 (στήλες):", np.sum(B, axis=0))
print("sum axis=1 (γραμμές):", np.sum(B, axis=1))
print("mean axis=0:", np.mean(B, axis=0))
print("std axis=1:", np.std(B, axis=1))
print("max:", np.max(B), "min:", np.min(B))


8. Reshape / Ravel / Flatten / Stacking

In [23]:
C = np.arange(8)
print("reshape 2x4:\n", C.reshape(2,4))

# Προσοχή: ravel -> view (όπου γίνεται), flatten -> πάντα νέο array (copy)
D = np.arange(6).reshape(2,3)
rv = D.ravel()
fl = D.flatten()
D[0,0] = 999
print("D μετά:", D)
print("ravel (view) βλέπει αλλαγή:", rv)
print("flatten (copy) ΔΕΝ αλλάζει:", fl)

# Concatenate / vstack / hstack
X = np.ones((2,2))
Y = np.zeros((2,2))
print("concatenate κατά άξονα 0:\n", np.concatenate([X, Y], axis=0))
print("vstack:\n", np.vstack([X, Y]))
print("hstack:\n", np.hstack([X, Y]))


reshape 2x4:
 [[0 1 2 3]
 [4 5 6 7]]
D μετά: [[999   1   2]
 [  3   4   5]]
ravel (view) βλέπει αλλαγή: [999   1   2   3   4   5]
flatten (copy) ΔΕΝ αλλάζει: [0 1 2 3 4 5]
concatenate κατά άξονα 0:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
vstack:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
hstack:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


9. Vectorization vs Loops (%%timeit)

In [12]:
# Προσοχή: τρέχει μόνο σε Jupyter ως cell magic
N = 1_000_000
arr = np.random.rand(N)

# Loop
def square_loop(a):
    out = np.empty_like(a)
    for i in range(a.size):
        out[i] = a[i]*a[i]
    return out

# Vectorized
def square_vec(a):
    return a*a

%timeit square_loop(arr)   
%timeit square_vec(arr)    


326 ms ± 25.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.59 ms ± 152 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Mini Ασκήσεις

3.1 Ευκλείδεια απόσταση (χωρίς loop)

Ζήτηση: Δοθέντα δύο διανύσματα u, v ίδιου μήκους, υπολόγισε την απόσταση \( |u - v|_2 \).

Hint: np.linalg.norm(u - v)

Λύση:

In [13]:
u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 6.0, 8.0])

dist = np.linalg.norm(u - v)  # ή np.sqrt(np.sum((u-v)**2))
dist


np.float64(7.0710678118654755)

3.2 Standardization (z‑score) ανά στήλη σε 2D array

Ζήτηση: Για A σχήματος (n_samples, n_features), αφαίρεσε το mean ανά στήλη και διαίρεσε με std ανά στήλη.

Προσοχή: Απόφυγε division by zero όταν std=0.

Λύση:

In [14]:
A = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])

col_mean = A.mean(axis=0)
col_std  = A.std(axis=0, ddof=0)  # population std
safe_std = np.where(col_std==0, 1.0, col_std)
A_z = (A - col_mean) / safe_std

A_z, A_z.mean(axis=0), A_z.std(axis=0)


(array([[-1.22474487, -1.22474487, -1.22474487],
        [ 0.        ,  0.        ,  0.        ],
        [ 1.22474487,  1.22474487,  1.22474487]]),
 array([0., 0., 0.]),
 array([1., 1., 1.]))

3.3 Dot product, elementwise product, covariance matrix

Ζήτηση:

Υπολόγισε dot product δύο διανυσμάτων.

Δείξε διαφορά με elementwise πολλαπλασιασμό.

Υπολόγισε covariance matrix και σχολίασε.

Hint: np.dot(a, b) vs a*b, np.cov(X, rowvar=False).

Λύση:

In [3]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

dot_ab = np.dot(a, b)   # scalar
elem   = a * b          # elementwise

# Dataset: 5 samples, 3 features
X = np.random.rand(5, 3)
# rowvar=False: κάθε στήλη = feature
cov = np.cov(X, rowvar=False, ddof=1)

dot_ab, elem, cov.shape, cov
# Το dot δίνει ένα scalar (ή matrix multiplication σε 2D), το * είναι στοιχείο‑προς‑στοιχείο. Το np.cov επιστρέφει μήτρα συνδιακύμανσης (features × features).

(np.int64(140),
 array([10, 40, 90]),
 (3, 3),
 array([[ 0.09338628, -0.11086559, -0.02943783],
        [-0.11086559,  0.18770817,  0.0336127 ],
        [-0.02943783,  0.0336127 ,  0.12511719]]))